name: Docker Build
on:
  push:
    tags: # 仅带 tag:v* 时构建
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # 登录 docker hub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
        # DOCKER_USERNAME 是 docker hub 账号名.
        # DOCKER_TOKEN: docker hub => Account Setting => Security 创建.
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ddg-email-panel:latest
